condense_wildcard_suffixes = true
error_on_line_overflow_comments = false
fn_single_line = false
max_width = 120
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
use_try_shorthand = true
